### ISSUE TITLE
百度 OCR 设置为日语，报如下错误

### ISSUE THREAD

**Issue by jiulinxiri** [drsanwujiang/video-timeline-and-subtitle-extract#2]
![image](https://user-images.githubusercontent.com/8756019/71798456-1dff1600-308d-11ea-8ace-7f352cad3db9.png)
错误内容不能拷贝，只能截个图

**Comment by drsanwujiang** [comment]
编码问题，更新了一下ocr.py，替换一下就应该正常了。

**Comment by jiulinxiri** [comment]
> 编码问题，更新了一下ocr.py，替换一下就应该正常了。

没问题了，感谢 @drsanwujiang 
![image](https://user-images.githubusercontent.com/8756019/71803244-36762d00-309b-11ea-9c5f-09da7e76ef68.png)
